#!/bin/bash

#BSUB -J "freq[1-22]%10"
#BSUB -R "rusage[mem=15000]"
#BSUB -n 2
#BSUB -W 24:00
#BSUB -o log.%J.%I
#BSUB -e err.%J.%I

chr="chr"$LSB_JOBINDEX
file=dwarfAllies.minDP5.max0.5N.minQ30.minGQ20.mac2.${chr}.vcf.gz

#for group in kagera detrizoo predator dwarfPred kivu
for group in kivu
do
 vcftools15 --gzvcf $file --freq2 --out ${group}_${chr}_dwarfAllies \
   --keep ${group}_dwarfAllies
done
