
#!/bin/bash

#BSUB -J "freq[1-22]%22"
#BSUB -n 1
#BSUB -W 12:00
#BSUB -o log.%J.%I
#BSUB -e err.%J.%I
#BSUB -R "rusage[mem=3000]"

module load gcc/4.8.2 gdc perl/5.18.4 zlib/1.2.8 vcftools/0.1.16

path=/cluster/work/gdc/shared/p500/victoriaGenomes/vcf/

CHR=chr${LSB_JOBINDEX}

#for group in [VAK]*_piscivore [AK]*_nonpiscivore Victoria_nonpiscivores.nonNubila
#for group in Victoria_insectivore_nubs
#for group in Kagera_nonpiscivore Victoria_Ikimba Kagera_piscivore Victoria_Burigi Victoria_Nabugabo
#for group in EdKi_paedophage Victoria_paedophage Victoria_nonpaedophage EdKi_nonpaedophage
#for group in Victoria_nonpaedophage
#for group in EdKi_paedophage
#for group in `cat ecoGroups.new`
#for group in `cat newGroups.non`
#for group in `cat newGroups.otherLakes`
#for group in Edward_non_epiphytic_algae_scraper Edward_epiphytic_algae_scraper
#for group in `cat new.list`
#for group in Congo Nile
#for group in Victoria Victoria_non_Pundamilia
#for group in Victoria_epiphytic_algae_scraper_purYel Victoria_core_Pundamilia
#for group in Victoria_non_Gaurochromis Victoria_non_detritivore Victoria_detritivore_E1 Victoria_Ptyochromis_sp_striped_rock_sheller_oral_sheller 
#for group in Victoria_non_insectivore 
#for group in Victoria_Paralabidochromis_chilotes_insect
#for group in Victoria_mitoXysti
#for group in Victoria_crabs Victoria_insectivore.dw Victoria_zooplanktivore.nyer Victoria_oral_sheller_Pty Victoria_oral_crusher_MacBicolor
#for group in crabs_eater detritivore epilithic_algae_scraper epiphytic_algae_scraper insectivore oral_crusher oral_sheller paedophage pharyngeal_mollusc_crusher piscivore zooplanktivore
#for group in "Victoria_non_"$group
#for group in Victoria_zooplanktivore.nyer
#for group in Victoria_oral_sheller_plagiodon Victoria_oral_sheller_all
#for group in Victoria_insectivore_Paral
#for group in Victoria_insectivore_dwRuf
#for group in Victoria_non_piscivore
#for group in Victoria_insectivore_Pund
#for group in Victoria_mitoXysti
#for group in Victoria_insectivore_Lith
#for group in Victoria_piscivore
#for group in Victoria_insectivore_rockpicker 
#for group in Victoria_Neo_rockpicker
#for group in Victoria_Northern_generalists
#for group in Victoria_epilithic_algae_scraper_Mbipia
#for group in Victoria_non_epilithic_scraper Victoria_epilithic_algae_scraper_Neo Victoria_non_epilithic_algae_scraper.noNeoRelatives

# Run vcftools to get allele frequencies for the groups of interest

for group in Victoria_nonZooplanktivore_nonPiscivore Victoria_piscivore Victoria_non_piscivore Victoria_Northern_generalists Victoria_mitoXysti 
do
 mkdir -p /cluster/scratch/meierjo/eco/freq_$group
 file=allGenomes.$CHR.SNPs.minDP6.minGQ20.max0.5N.3masks.vcf.gz
 vcftools --max-alleles 2 --remove-indels --gzvcf ${path}${file} --keep $group.inds \
  --freq2 --out /cluster/scratch/meierjo/eco/freq_$group/$group.$CHR
 cp /cluster/scratch/meierjo/eco/freq_$group/$group.$CHR* ./
done
